# Movie Recommendation System

We will implement and understand the basic Recommender System Techniques.
This Involves Content based filtering and Collaborative Filtering Techniques for the Recommender System.

In [1]:
import pandas as pd
import numpy as np

In [2]:
rating_df = pd.read_csv('./data/ratings.csv')
movies_df = pd.read_csv('./data/movies.csv')

In [3]:
rating_df.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [4]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

Keeping Important features in the dataframe and meriging them.

In [5]:
movie = movies_df[['movieId','title']]

In [6]:
rating = rating_df[['userId','movieId','rating']]

In [7]:
ratings = pd.merge(movie, rating)

ratings.head()

   movieId             title  userId  rating
0        1  Toy Story (1995)       7     3.0
1        1  Toy Story (1995)       9     4.0
2        1  Toy Story (1995)      13     5.0
3        1  Toy Story (1995)      15     2.0
4        1  Toy Story (1995)      19     3.0

In [8]:
movie.head()

   movieId                               title
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

In [9]:
rating.head()

   userId  movieId  rating
0       1       31     2.5
1       1     1029     3.0
2       1     1061     3.0
3       1     1129     2.0
4       1     1172     4.0

In [10]:
movieRatings = ratings.pivot_table(index=['userId'],columns=['title'],values=['rating'])
movieRatings.head()

                                 rating               \
title  "Great Performances" Cats (1998) $9.99 (2008)
userId
1                                   NaN          NaN
2                                   NaN          NaN
3                                   NaN          NaN
4                                   NaN          NaN
5                                   NaN          NaN

                                                \
title  'Hellboy': The Seeds of Creation (2004)
userId
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
5                                          NaN

                                                               \
title  'Neath the Arizona Skies (1934) 'Round Midnight (1986)
userId
1                                  NaN                    NaN
2                                  NaN                    NaN
3                                  NaN                    NaN
4                                  NaN                    NaN
5                                  NaN                    NaN

                                                                         \
title  'Salem's Lot (2004) 'Til There Was You (1997) 'burbs, The (1989)
userId
1                      NaN                       NaN                NaN
2                      NaN                       NaN                NaN
3                      NaN                       NaN                NaN
4                      NaN                       NaN                NaN
5                      NaN                       NaN                NaN

                                                                ...          \
title  'night Mother (1986) (500) Days of Summer (2009)         ...
userId                                                          ...
1                       NaN                         NaN         ...
2                       NaN                         NaN         ...
3                       NaN                         NaN         ...
4                       NaN                         NaN         ...
5                       NaN                         NaN         ...

                                                             \
title  Zulu (1964) Zulu (2013) [REC] (2007) eXistenZ (1999)
userId
1              NaN         NaN          NaN             NaN
2              NaN         NaN          NaN             NaN
3              NaN         NaN          NaN             NaN
4              NaN         NaN          NaN             NaN
5              NaN         NaN          NaN             NaN

                                                                 \
title  loudQUIETloud: A Film About the Pixies (2006) xXx (2002)
userId
1                                                NaN        NaN
2                                                NaN        NaN
3                                                NaN        NaN
4                                                NaN        NaN
5                                                NaN        NaN

                                                             \
title  xXx: State of the Union (2005) ¡Three Amigos! (1986)
userId
1                                 NaN                   NaN
2                                 NaN                   NaN
3                                 NaN                   NaN
4                                 NaN                   NaN
5                                 NaN                   NaN


title  À nous la liberté (Freedom for Us) (1931) İtirazım Var (2014)
userId
1                                            NaN                 NaN
2                                            NaN                 NaN
3                                            NaN                 NaN
4                                            NaN                 NaN
5                                            NaN                 NaN

[5 rows x 9064 columns]

In [11]:
movieRatings.shape

(671, 9064)

In [12]:
movie['title'].nunique()

9123

In [13]:
ratings['userId'].nunique()

671

In [14]:
ratings[ratings.userId==1]

       movieId                                           title  userId  rating
1611        31                          Dangerous Minds (1995)       1     2.5
25005     1029                                    Dumbo (1941)       1     3.0
25708     1061                                 Sleepers (1996)       1     3.0
27330     1129                     Escape from New York (1981)       1     2.0
27748     1172  Cinema Paradiso (Nuovo cinema Paradiso) (1989)       1     4.0
32415     1263                         Deer Hunter, The (1978)       1     2.0
33591     1287                                  Ben-Hur (1959)       1     2.0
33919     1293                                   Gandhi (1982)       1     2.0
34595     1339          Dracula (Bram Stoker's Dracula) (1992)       1     3.5
34676     1343                                Cape Fear (1991)       1     2.0
35240     1371            Star Trek: The Motion Picture (1979)       1     2.5
36296     1405          Beavis and Butt-Head Do America (1996)       1     1.0
42652     1953                   French Connection, The (1971)       1     4.0
45732     2105                                     Tron (1982)       1     4.0
46638     2150                  Gods Must Be Crazy, The (1980)       1     3.0
47102     2193                                   Willow (1988)       1     2.0
48032     2294                                     Antz (1998)       1     2.0
50594     2455                                 Fly, The (1986)       1     2.5
57542     2968                             Time Bandits (1981)       1     1.0
64583     3671                          Blazing Saddles (1974)       1     3.0

Let's fetch list of movies containg word 'Star' in its tittle.

In [15]:
movieRatings.loc[:,'rating'].columns.str.contains('Star').any()

True

In [16]:
movie[movie.title.str.contains('Star Wars')]

      movieId                                              title
232       260          Star Wars: Episode IV - A New Hope (1977)
953      1196  Star Wars: Episode V - The Empire Strikes Back...
966      1210  Star Wars: Episode VI - Return of the Jedi (1983)
2103     2628   Star Wars: Episode I - The Phantom Menace (1999)
4103     5378  Star Wars: Episode II - Attack of the Clones (...
6139    33493  Star Wars: Episode III - Revenge of the Sith (...
7023    61160                   Star Wars: The Clone Wars (2008)
7570    79006  Empire of Dreams: The Story of the 'Star Wars'...
8783   122886  Star Wars: Episode VII - The Force Awakens (2015)

We will now try to find movies similar to Star Wars.

In [17]:
movieRatings.loc[:,'rating']['Star Wars: Episode IV - A New Hope (1977)']

userId
1      NaN
2      NaN
3      NaN
4      5.0
5      NaN
6      NaN
7      5.0
8      3.5
9      NaN
10     NaN
11     NaN
12     NaN
13     NaN
14     NaN
15     5.0
16     NaN
17     3.5
18     3.0
19     4.0
20     1.5
21     3.0
22     4.0
23     4.5
24     NaN
25     4.0
26     3.0
27     NaN
28     NaN
29     NaN
30     4.0
      ...
642    NaN
643    5.0
644    NaN
645    NaN
646    5.0
647    5.0
648    NaN
649    NaN
650    NaN
651    5.0
652    NaN
653    NaN
654    5.0
655    2.5
656    NaN
657    NaN
658    NaN
659    5.0
660    4.5
661    NaN
662    NaN
663    NaN
664    4.5
665    4.0
666    NaN
667    NaN
668    NaN
669    5.0
670    NaN
671    5.0
Name: Star Wars: Episode IV - A New Hope (1977), Length: 671, dtype: float64

In [18]:
starWarsRatings = movieRatings.loc[:,'rating']['Star Wars: Episode IV - A New Hope (1977)']

In [19]:
starWarsRatings.head()

userId
1    NaN
2    NaN
3    NaN
4    5.0
5    NaN
Name: Star Wars: Episode IV - A New Hope (1977), dtype: float64

In [20]:
similarMovies = movieRatings.corrwith(starWarsRatings)
similarMovies = similarMovies.dropna()
df = pd.DataFrame(similarMovies)
df.head(10)

/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py:3175: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)
/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py:3109: RuntimeWarning: divide by zero encountered in double_scalars
  c *= 1. / np.float64(fact)

                                                                  0
       title
rating 'burbs, The (1989)                                  0.233314
       (500) Days of Summer (2009)                         0.074535
       *batteries not included (1987)                     -0.298541
       ...And Justice for All (1979)                      -0.312428
       10 (1979)                                          -0.500000
       10 Cloverfield Lane (2016)                         -0.771517
       10 Things I Hate About You (1999)                   0.203774
       10,000 BC (2008)                                   -0.560612
       101 Dalmatians (1996)                               0.366918
       101 Dalmatians (One Hundred and One Dalmatians)...  0.135368

In [21]:
similarMovies.sort_values(ascending=False)

        title
rating  Pet Sematary II (1992)                                             1.0
        Jetée, La (1962)                                                   1.0
        Daddy Day Care (2003)                                              1.0
        Simple Wish, A (1997)                                              1.0
        Ichi the Killer (Koroshiya 1) (2001)                               1.0
        Claymation Christmas Celebration, A (1987)                         1.0
        Shakes the Clown (1992)                                            1.0
        Clean Slate (1994)                                                 1.0
        Whisper of the Heart (Mimi wo sumaseba) (1995)                     1.0
        The Skeleton Twins (2014)                                          1.0
        Eat Pray Love (2010)                                               1.0
        Philomena (2013)                                                   1.0
        Pursuit of Happiness (2001)                                        1.0
        The Wedding Ringer (2015)                                          1.0
        Stepfather, The (1987)                                             1.0
        Whatever Works (2009)                                              1.0
        Here Comes the Boom (2012)                                         1.0
        Exterminating Angel, The (Ángel exterminador, El) (1962)           1.0
        Puppet Master (1989)                                               1.0
        Edge of Seventeen (1998)                                           1.0
        U.S. vs. John Lennon, The (2006)                                   1.0
        Little Monsters (1989)                                             1.0
        Star Wars: Episode IV - A New Hope (1977)                          1.0
        Legend, The (Legend of Fong Sai-Yuk, The) (Fong Sai Yuk) (1993)    1.0
        Tsotsi (2005)                                                      1.0
        Wings (1927)                                                       1.0
        Tuck Everlasting (2002)                                            1.0
        Leap of Faith (1992)                                               1.0
        My Name Is Joe (1998)                                              1.0
        Farmer's Daughter, The (1947)                                      1.0
                                                                          ...
        Charlie Bartlett (2007)                                           -1.0
        Grace of My Heart (1996)                                          -1.0
        Headhunters (Hodejegerne) (2011)                                  -1.0
        Monsieur Verdoux (1947)                                           -1.0
        Rage: Carrie 2, The (1999)                                        -1.0
        All Is Lost (2013)                                                -1.0
        Blue Collar (1978)                                                -1.0
        If.... (1968)                                                     -1.0
        Wings of the Dove, The (1997)                                     -1.0
        American Rhapsody, An (2001)                                      -1.0
        Book of Shadows: Blair Witch 2 (2000)                             -1.0
        Scooby-Doo 2: Monsters Unleashed (2004)                           -1.0
        Human Nature (2001)                                               -1.0
        Deadly Friend (1986)                                              -1.0
        Sunrise: A Song of Two Humans (1927)                              -1.0
        How to Stuff a Wild Bikini (1965)                                 -1.0
        Under the Rainbow (1981)                                          -1.0
        Brain That Wouldn't Die, The (1962)                               -1.0
        Middle Men (2009)                                                 -1.0
        Seeking a Friend for the End of the World (2012)                  -1.0
        House Arrest (1996)                                               -1.0
        Hot Rod (2007)                                                    -1.0
        Horror Express (1972)                                             -1.0
        Million Dollar Hotel, The (2001)                                  -1.0
        TPB AFK: The Pirate Bay Away from Keyboard (2013)                 -1.0
        Piranha (1978)                                                    -1.0
        Hideaway (1995)                                                   -1.0
        Hidden, The (1987)                                                -1.0
        Shadow, The (1994)                                                -1.0
        It Might Get Loud (2008)                                          -1.0
Length: 4496, dtype: float64

In [22]:
movieStats = ratings.groupby('title').agg({'rating':[np.size,np.mean]})
movieStats.head()

                                        rating
                                          size      mean
title
"Great Performances" Cats (1998)           2.0  1.750000
$9.99 (2008)                               3.0  3.833333
'Hellboy': The Seeds of Creation (2004)    1.0  2.000000
'Neath the Arizona Skies (1934)            1.0  0.500000
'Round Midnight (1986)                     2.0  2.250000

In [23]:
popularMovies = movieStats['rating']['size'] >= 100
movieStats[popularMovies].sort_values([('rating','mean')],ascending=False)[:15]

                                                   rating
                                                     size      mean
title
Godfather, The (1972)                               200.0  4.487500
Shawshank Redemption, The (1994)                    311.0  4.487138
Godfather: Part II, The (1974)                      135.0  4.385185
Usual Suspects, The (1995)                          201.0  4.370647
Schindler's List (1993)                             244.0  4.303279
One Flew Over the Cuckoo's Nest (1975)              144.0  4.256944
Fargo (1996)                                        224.0  4.256696
Pulp Fiction (1994)                                 324.0  4.256173
American Beauty (1999)                              220.0  4.236364
Dark Knight, The (2008)                             121.0  4.235537
Casablanca (1942)                                   117.0  4.235043
Star Wars: Episode V - The Empire Strikes Back ...  234.0  4.232906
Memento (2000)                                      132.0  4.227273
Taxi Driver (1976)                                  118.0  4.224576
Monty Python and the Holy Grail (1975)              145.0  4.224138

In [24]:
df = movieStats[popularMovies].join(pd.DataFrame(similarMovies,columns=['similarity']))

/anaconda3/lib/python3.6/site-packages/pandas/core/reshape/merge.py:543: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)

In [25]:
df.head()

                                          (rating, size)  (rating, mean)  \
       title
rating 2001: A Space Odyssey (1968)                123.0        3.886179
       Ace Ventura: Pet Detective (1994)           175.0        2.871429
       Airplane! (1980)                            106.0        3.820755
       Aladdin (1992)                              215.0        3.674419
       Alien (1979)                                127.0        3.988189

                                          similarity
       title
rating 2001: A Space Odyssey (1968)         0.128119
       Ace Ventura: Pet Detective (1994)    0.282704
       Airplane! (1980)                     0.115171
       Aladdin (1992)                       0.184296
       Alien (1979)                         0.088017

In [26]:
df.sort_values(['similarity'],ascending =False)[:15]

                                                           (rating, size)  \
       title
rating Star Wars: Episode IV - A New Hope (1977)                    291.0
       Star Wars: Episode VI - Return of the Jedi (1983)            217.0
       Star Wars: Episode V - The Empire Strikes Back ...           234.0
       Dark Knight, The (2008)                                      121.0
       Lord of the Rings: The Fellowship of the Ring, ...           200.0
       Raiders of the Lost Ark (Indiana Jones and the ...           220.0
       Incredibles, The (2004)                                      126.0
       Lord of the Rings: The Two Towers, The (2002)                188.0
       E.T. the Extra-Terrestrial (1982)                            160.0
       Star Trek: Generations (1994)                                114.0
       Monsters, Inc. (2001)                                        130.0
       Big (1988)                                                   107.0
       Lord of the Rings: The Return of the King, The ...           176.0
       Toy Story 2 (1999)                                           125.0
       Babe (1995)                                                  148.0

                                                           (rating, mean)  \
       title
rating Star Wars: Episode IV - A New Hope (1977)                 4.221649
       Star Wars: Episode VI - Return of the Jedi (1983)         4.059908
       Star Wars: Episode V - The Empire Strikes Back ...        4.232906
       Dark Knight, The (2008)                                   4.235537
       Lord of the Rings: The Fellowship of the Ring, ...        4.182500
       Raiders of the Lost Ark (Indiana Jones and the ...        4.193182
       Incredibles, The (2004)                                   3.861111
       Lord of the Rings: The Two Towers, The (2002)             4.061170
       E.T. the Extra-Terrestrial (1982)                         3.768750
       Star Trek: Generations (1994)                             3.350877
       Monsters, Inc. (2001)                                     3.884615
       Big (1988)                                                3.831776
       Lord of the Rings: The Return of the King, The ...        4.127841
       Toy Story 2 (1999)                                        3.844000
       Babe (1995)                                               3.601351

                                                           similarity
       title
rating Star Wars: Episode IV - A New Hope (1977)             1.000000
       Star Wars: Episode VI - Return of the Jedi (1983)     0.747774
       Star Wars: Episode V - The Empire Strikes Back ...    0.700790
       Dark Knight, The (2008)                               0.549486
       Lord of the Rings: The Fellowship of the Ring, ...    0.477582
       Raiders of the Lost Ark (Indiana Jones and the ...    0.476442
       Incredibles, The (2004)                               0.450914
       Lord of the Rings: The Two Towers, The (2002)         0.448153
       E.T. the Extra-Terrestrial (1982)                     0.428289
       Star Trek: Generations (1994)                         0.413682
       Monsters, Inc. (2001)                                 0.403180
       Big (1988)                                            0.393398
       Lord of the Rings: The Return of the King, The ...    0.383217
       Toy Story 2 (1999)                                    0.374929
       Babe (1995)                                           0.374293

## Item-Based Collaborative Filtering

In [27]:
userRatings = ratings.pivot_table(index='userId',columns='title',values='rating')
userRatings.head()

title,"""Great Performances"" Cats (1998)",$9.99 (2008),'Hellboy': The Seeds of Creation (2004),'Neath the Arizona Skies (1934),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),...,Zulu (1964),Zulu (2013),[REC] (2007),eXistenZ (1999),loudQUIETloud: A Film About the Pixies (2006),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931),İtirazım Var (2014)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
corrMatrix = userRatings.corr()
corrMatrix.head()

title,"""Great Performances"" Cats (1998)",$9.99 (2008),'Hellboy': The Seeds of Creation (2004),'Neath the Arizona Skies (1934),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),...,Zulu (1964),Zulu (2013),[REC] (2007),eXistenZ (1999),loudQUIETloud: A Film About the Pixies (2006),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931),İtirazım Var (2014)
title,,,,,,,,,,,,,,,,,,,,,
"""Great Performances"" Cats (1998)",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
$9.99 (2008),NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Hellboy': The Seeds of Creation (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Neath the Arizona Skies (1934),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Round Midnight (1986),NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
corrMatrix = userRatings.corr(method='pearson', min_periods=100)
corrMatrix.head()

title,"""Great Performances"" Cats (1998)",$9.99 (2008),'Hellboy': The Seeds of Creation (2004),'Neath the Arizona Skies (1934),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),...,Zulu (1964),Zulu (2013),[REC] (2007),eXistenZ (1999),loudQUIETloud: A Film About the Pixies (2006),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931),İtirazım Var (2014)
title,,,,,,,,,,,,,,,,,,,,,
"""Great Performances"" Cats (1998)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
$9.99 (2008),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Hellboy': The Seeds of Creation (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Neath the Arizona Skies (1934),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Round Midnight (1986),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
myRatings = userRatings.loc[3].dropna()
myRatings

title
Aladdin (1992)                                                 3.0
American Beauty (1999)                                         4.0
Batman (1989)                                                  3.0
Beauty and the Beast (1991)                                    2.0
Big Daddy (1999)                                               3.0
Bound (1996)                                                   3.0
Bowling for Columbine (2002)                                   3.5
Braveheart (1995)                                              4.0
Daria: Is It Fall Yet? (2000)                                  3.5
Dark Knight, The (2008)                                        3.0
Encino Man (1992)                                              3.0
Eternal Sunshine of the Spotless Mind (2004)                   3.0
Fahrenheit 9/11 (2004)                                         3.5
Fear and Loathing in Las Vegas (1998)                          4.0
Fight Club (1999)                                              5.0
Finding Nemo (2003)                                            3.0
Flags of Our Fathers (2006)                                    4.5
Flintstones, The (1994)                                        2.5
Forrest Gump (1994)                                            5.0
Frequency (2000)                                               4.0
Fried Green Tomatoes (1991)                                    3.0
Ghostbusters (a.k.a. Ghost Busters) (1984)                     3.0
Happiness (1998)                                               4.0
Harold and Maude (1971)                                        4.0
Heavenly Creatures (1994)                                      3.5
Indian in the Cupboard, The (1995)                             3.0
Letters from Iwo Jima (2006)                                   4.5
Lord of the Rings: The Return of the King, The (2003)          2.5
Major Payne (1995)                                             3.0
Men in Black (a.k.a. MIB) (1997)                               3.5
Pet Sematary (1989)                                            3.0
Princess Bride, The (1987)                                     5.0
Pulp Fiction (1994)                                            4.5
Requiem for a Dream (2000)                                     5.0
Saving Private Ryan (1998)                                     4.0
Schindler's List (1993)                                        3.0
Shawshank Redemption, The (1994)                               5.0
Silence of the Lambs, The (1991)                               3.0
Sixth Sense, The (1999)                                        3.5
Speed (1994)                                                   2.5
Spider-Man (2002)                                              3.0
Spider-Man 2 (2004)                                            3.0
Star Wars: Episode VI - Return of the Jedi (1983)              3.0
Stir of Echoes (1999)                                          4.0
Summer of Sam (1999)                                           3.5
Titanic (1997)                                                 4.5
Trainspotting (1996)                                           4.0
Twister (1996)                                                 3.5
V for Vendetta (2006)                                          3.5
White Stripes Under Great White Northern Lights, The (2009)    4.0
Young Guns (1988)                                              4.0
Name: 3, dtype: float64

In [31]:
simCandidates = pd.Series()
for i in range(0,len(myRatings.index)):
    print("Adding sims for "+myRatings.index[i]+"...")
    sims = corrMatrix[myRatings.index[i]].dropna()
    sims = sims.map(lambda x:x*myRatings[i])
    simCandidates = simCandidates.append(sims)
print("sorting...")
simCandidates.sort_values(inplace=True,ascending =False)
simCandidates.head(10)

Adding sims for Aladdin (1992)...
Adding sims for American Beauty (1999)...
Adding sims for Batman (1989)...
Adding sims for Beauty and the Beast (1991)...
Adding sims for Big Daddy (1999)...
Adding sims for Bound (1996)...
Adding sims for Bowling for Columbine (2002)...
Adding sims for Braveheart (1995)...
Adding sims for Daria: Is It Fall Yet? (2000)...
Adding sims for Dark Knight, The (2008)...
Adding sims for Encino Man (1992)...
Adding sims for Eternal Sunshine of the Spotless Mind (2004)...
Adding sims for Fahrenheit 9/11 (2004)...
Adding sims for Fear and Loathing in Las Vegas (1998)...
Adding sims for Fight Club (1999)...
Adding sims for Finding Nemo (2003)...
Adding sims for Flags of Our Fathers (2006)...
Adding sims for Flintstones, The (1994)...
Adding sims for Forrest Gump (1994)...
Adding sims for Frequency (2000)...
Adding sims for Fried Green Tomatoes (1991)...
Adding sims for Ghostbusters (a.k.a. Ghost Busters) (1984)...
Adding sims for Happiness (1998)...
Adding sims for Harold and Maude (1971)...
Adding sims for Heavenly Creatures (1994)...
Adding sims for Indian in the Cupboard, The (1995)...
Adding sims for Letters from Iwo Jima (2006)...
Adding sims for Lord of the Rings: The Return of the King, The (2003)...
Adding sims for Major Payne (1995)...
Adding sims for Men in Black (a.k.a. MIB) (1997)...
Adding sims for Pet Sematary (1989)...
Adding sims for Princess Bride, The (1987)...
Adding sims for Pulp Fiction (1994)...
Adding sims for Requiem for a Dream (2000)...
Adding sims for Saving Private Ryan (1998)...
Adding sims for Schindler's List (1993)...
Adding sims for Shawshank Redemption, The (1994)...
Adding sims for Silence of the Lambs, The (1991)...
Adding sims for Sixth Sense, The (1999)...
Adding sims for Speed (1994)...
Adding sims for Spider-Man (2002)...
Adding sims for Spider-Man 2 (2004)...
Adding sims for Star Wars: Episode VI - Return of the Jedi (1983)...
Adding sims for Stir of Echoes (1999)...
Adding sims for Summer of Sam (1999)...
Adding sims for Titanic (1997)...
Adding sims for Trainspotting (1996)...
Adding sims for Twister (1996)...
Adding sims for V for Vendetta (2006)...
Adding sims for White Stripes Under Great White Northern Lights, The (2009)...
Adding sims for Young Guns (1988)...
sorting...

Fight Club (1999)                   5.0
Forrest Gump (1994)                 5.0
Princess Bride, The (1987)          5.0
Shawshank Redemption, The (1994)    5.0
Titanic (1997)                      4.5
Pulp Fiction (1994)                 4.5
Braveheart (1995)                   4.0
American Beauty (1999)              4.0
Trainspotting (1996)                4.0
Saving Private Ryan (1998)          4.0
dtype: float64

In [32]:
simCandidates = simCandidates.groupby(simCandidates.index).sum()

In [33]:
simCandidates.sort_values(inplace=True,ascending=False)
simCandidates.head(10)

Shawshank Redemption, The (1994)                                                  20.198580
Forrest Gump (1994)                                                               19.983816
Jurassic Park (1993)                                                              16.678243
Toy Story (1995)                                                                  15.568640
Braveheart (1995)                                                                 15.478404
Star Wars: Episode IV - A New Hope (1977)                                         15.248237
Saving Private Ryan (1998)                                                        14.690872
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    13.782332
Back to the Future (1985)                                                         13.613303
Silence of the Lambs, The (1991)                                                  13.296801
dtype: float64

In [35]:
remove_list =[]
for i in simCandidates.index:
    for j in myRatings.index:
        if i==j:
            remove_list.append(i)
remove_list

['Shawshank Redemption, The (1994)',
 'Forrest Gump (1994)',
 'Braveheart (1995)',
 'Saving Private Ryan (1998)',
 'Silence of the Lambs, The (1991)',
 "Schindler's List (1993)",
 'Men in Black (a.k.a. MIB) (1997)',
 'Aladdin (1992)',
 'Fight Club (1999)',
 'Sixth Sense, The (1999)',
 'American Beauty (1999)',
 'Pulp Fiction (1994)',
 'Titanic (1997)',
 'Star Wars: Episode VI - Return of the Jedi (1983)',
 'Princess Bride, The (1987)',
 'Beauty and the Beast (1991)',
 'Lord of the Rings: The Return of the King, The (2003)',
 'Speed (1994)',
 'Batman (1989)',
 'Spider-Man (2002)',
 'Twister (1996)',
 'Trainspotting (1996)',
 'Ghostbusters (a.k.a. Ghost Busters) (1984)',
 'Eternal Sunshine of the Spotless Mind (2004)',
 'Dark Knight, The (2008)',
 'Finding Nemo (2003)']

In [36]:
simCandidates[remove_list]

Shawshank Redemption, The (1994)                         20.198580
Forrest Gump (1994)                                      19.983816
Braveheart (1995)                                        15.478404
Saving Private Ryan (1998)                               14.690872
Silence of the Lambs, The (1991)                         13.296801
Schindler's List (1993)                                  13.258478
Men in Black (a.k.a. MIB) (1997)                         12.544456
Aladdin (1992)                                           12.118870
Fight Club (1999)                                        11.950291
Sixth Sense, The (1999)                                  11.887038
American Beauty (1999)                                   11.353806
Pulp Fiction (1994)                                      10.523285
Titanic (1997)                                            9.986994
Star Wars: Episode VI - Return of the Jedi (1983)         9.684901
Princess Bride, The (1987)                                7.670158
Beauty and the Beast (1991)                               7.583602
Lord of the Rings: The Return of the King, The (2003)     6.583877
Speed (1994)                                              6.217424
Batman (1989)                                             5.705761
Spider-Man (2002)                                         5.381342
Twister (1996)                                            4.344314
Trainspotting (1996)                                      4.000000
Ghostbusters (a.k.a. Ghost Busters) (1984)                3.442995
Eternal Sunshine of the Spotless Mind (2004)              3.000000
Dark Knight, The (2008)                                   3.000000
Finding Nemo (2003)                                       3.000000
dtype: float64

In [37]:
myRatings['Shawshank Redemption, The (1994)']

5.0

In [38]:
simCandidates.drop(remove_list)

Jurassic Park (1993)                                                              16.678243
Toy Story (1995)                                                                  15.568640
Star Wars: Episode IV - A New Hope (1977)                                         15.248237
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    13.782332
Back to the Future (1985)                                                         13.613303
Star Wars: Episode V - The Empire Strikes Back (1980)                             11.985316
Lord of the Rings: The Fellowship of the Ring, The (2001)                         11.300383
Lion King, The (1994)                                                             10.432855
Independence Day (a.k.a. ID4) (1996)                                               9.613008
Lord of the Rings: The Two Towers, The (2002)                                      9.468344
Matrix, The (1999)                                                                 9.346084
Dances with Wolves (1990)                                                          8.612609
Fargo (1996)                                                                       7.787533
Shrek (2001)                                                                       7.470805
E.T. the Extra-Terrestrial (1982)                                                  6.959453
True Lies (1994)                                                                   6.847852
Apollo 13 (1995)                                                                   6.570148
Gladiator (2000)                                                                   6.546923
Usual Suspects, The (1995)                                                         6.513178
Terminator 2: Judgment Day (1991)                                                  6.438947
Seven (a.k.a. Se7en) (1995)                                                        5.991121
Ace Ventura: Pet Detective (1994)                                                  5.903033
Good Will Hunting (1997)                                                           5.663343
Groundhog Day (1993)                                                               5.611809
Die Hard (1988)                                                                    5.474117
Godfather, The (1972)                                                              5.354687
Mask, The (1994)                                                                   5.187759
Mrs. Doubtfire (1993)                                                              5.064983
Dumb & Dumber (Dumb and Dumber) (1994)                                             5.051165
Terminator, The (1984)                                                             4.173230
Pretty Woman (1990)                                                                3.717725
Babe (1995)                                                                        3.667345
Twelve Monkeys (a.k.a. 12 Monkeys) (1995)                                          3.525210
Indiana Jones and the Last Crusade (1989)                                          3.241530
Fugitive, The (1993)                                                               2.788352
Die Hard: With a Vengeance (1995)                                                  2.755249
Ghost (1990)                                                                       2.585878
One Flew Over the Cuckoo's Nest (1975)                                             2.448850
Reservoir Dogs (1992)                                                              2.372018
Truman Show, The (1998)                                                            2.296710
Star Wars: Episode I - The Phantom Menace (1999)                                   2.185591
Monty Python and the Holy Grail (1975)                                             2.114956
Goodfellas (1990)                                                                  1.967638
Home Alone (1990)                                                                  1.908440
Interview with the Vampire: The Vampire Chronicles (1994)                          1.904089
Stargate (1994)                                                                    1.896548
Memento (2000)                                                                     1.875949
Ocean's Eleven (2001)                                                              1.677435
Mission: Impossible (1996)                                                         1.587954
Sleepless in Seattle (1993)                                                        1.578389
Léon: The Professional (a.k.a. The Professional) (Léon) (1994)                     1.450572
Ferris Bueller's Day Off (1986)                                                    1.269489
Four Weddings and a Funeral (1994)                                                 1.090645
Clear and Present Danger (1994)                                                    1.084366
Pirates of the Caribbean: The Curse of the Black Pearl (2003)                      0.962370
Clueless (1995)                                                                    0.954752
Firm, The (1993)                                                                   0.918963
Batman Forever (1995)                                                              0.908869
GoldenEye (1995)                                                                   0.776046
dtype: float64

In [40]:
filtered_results = simCandidates.drop(remove_list)
filtered_results

Jurassic Park (1993)                                                              16.678243
Toy Story (1995)                                                                  15.568640
Star Wars: Episode IV - A New Hope (1977)                                         15.248237
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    13.782332
Back to the Future (1985)                                                         13.613303
Star Wars: Episode V - The Empire Strikes Back (1980)                             11.985316
Lord of the Rings: The Fellowship of the Ring, The (2001)                         11.300383
Lion King, The (1994)                                                             10.432855
Independence Day (a.k.a. ID4) (1996)                                               9.613008
Lord of the Rings: The Two Towers, The (2002)                                      9.468344
Matrix, The (1999)                                                                 9.346084
Dances with Wolves (1990)                                                          8.612609
Fargo (1996)                                                                       7.787533
Shrek (2001)                                                                       7.470805
E.T. the Extra-Terrestrial (1982)                                                  6.959453
True Lies (1994)                                                                   6.847852
Apollo 13 (1995)                                                                   6.570148
Gladiator (2000)                                                                   6.546923
Usual Suspects, The (1995)                                                         6.513178
Terminator 2: Judgment Day (1991)                                                  6.438947
Seven (a.k.a. Se7en) (1995)                                                        5.991121
Ace Ventura: Pet Detective (1994)                                                  5.903033
Good Will Hunting (1997)                                                           5.663343
Groundhog Day (1993)                                                               5.611809
Die Hard (1988)                                                                    5.474117
Godfather, The (1972)                                                              5.354687
Mask, The (1994)                                                                   5.187759
Mrs. Doubtfire (1993)                                                              5.064983
Dumb & Dumber (Dumb and Dumber) (1994)                                             5.051165
Terminator, The (1984)                                                             4.173230
Pretty Woman (1990)                                                                3.717725
Babe (1995)                                                                        3.667345
Twelve Monkeys (a.k.a. 12 Monkeys) (1995)                                          3.525210
Indiana Jones and the Last Crusade (1989)                                          3.241530
Fugitive, The (1993)                                                               2.788352
Die Hard: With a Vengeance (1995)                                                  2.755249
Ghost (1990)                                                                       2.585878
One Flew Over the Cuckoo's Nest (1975)                                             2.448850
Reservoir Dogs (1992)                                                              2.372018
Truman Show, The (1998)                                                            2.296710
Star Wars: Episode I - The Phantom Menace (1999)                                   2.185591
Monty Python and the Holy Grail (1975)                                             2.114956
Goodfellas (1990)                                                                  1.967638
Home Alone (1990)                                                                  1.908440
Interview with the Vampire: The Vampire Chronicles (1994)                          1.904089
Stargate (1994)                                                                    1.896548
Memento (2000)                                                                     1.875949
Ocean's Eleven (2001)                                                              1.677435
Mission: Impossible (1996)                                                         1.587954
Sleepless in Seattle (1993)                                                        1.578389
Léon: The Professional (a.k.a. The Professional) (Léon) (1994)                     1.450572
Ferris Bueller's Day Off (1986)                                                    1.269489
Four Weddings and a Funeral (1994)                                                 1.090645
Clear and Present Danger (1994)                                                    1.084366
Pirates of the Caribbean: The Curse of the Black Pearl (2003)                      0.962370
Clueless (1995)                                                                    0.954752
Firm, The (1993)                                                                   0.918963
Batman Forever (1995)                                                              0.908869
GoldenEye (1995)                                                                   0.776046
dtype: float64

In [49]:
movies_df.genres.str.contains('Comedy').head()

0     True
1    False
2     True
3     True
4     True
Name: genres, dtype: bool

In [75]:
genres = movies_df.genres.str.split('|',expand=True).dropna().values.tolist()[0]

In [76]:
genres

['Action',
 'Adventure',
 'Comedy',
 'Crime',
 'Drama',
 'Film-Noir',
 'Horror',
 'Mystery',
 'Thriller',
 'Western']

In [79]:
for i in genres:
    movies_df[i] = movies_df.genres.str.contains(i)
movies_df.head()

,movieId,title,genres,Action,Adventure,Comedy,Crime,Drama,Film-Noir,Horror,Mystery,Thriller,Western
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,False,True,True,False,False,False,False,False,False,False
1,2,Jumanji (1995),Adventure|Children|Fantasy,False,True,False,False,False,False,False,False,False,False
2,3,Grumpier Old Men (1995),Comedy|Romance,False,False,True,False,False,False,False,False,False,False
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,False,False,True,False,True,False,False,False,False,False
4,5,Father of the Bride Part II (1995),Comedy,False,False,True,False,False,False,False,False,False,False

In [85]:
movies_df = movies_df.drop('genres',axis=1)

In [92]:
movies_df['Year'] = movies_df.title.str.extract('.*\((.*)\).*', expand=True)

In [122]:
movies_df.set_index('title')

,movieId,Action,Adventure,Comedy,Crime,Drama,Film-Noir,Horror,Mystery,Thriller,Western,Year
title,,,,,,,,,,,,
Toy Story (1995),1,False,True,True,False,False,False,False,False,False,False,1995
Jumanji (1995),2,False,True,False,False,False,False,False,False,False,False,1995
Grumpier Old Men (1995),3,False,False,True,False,False,False,False,False,False,False,1995
Waiting to Exhale (1995),4,False,False,True,False,True,False,False,False,False,False,1995
Father of the Bride Part II (1995),5,False,False,True,False,False,False,False,False,False,False,1995
Heat (1995),6,True,False,False,True,False,False,False,False,True,False,1995
Sabrina (1995),7,False,False,True,False,False,False,False,False,False,False,1995
Tom and Huck (1995),8,False,True,False,False,False,False,False,False,False,False,1995
Sudden Death (1995),9,True,False,False,False,False,False,False,False,False,False,1995
GoldenEye (1995),10,True,True,False,False,False,False,False,False,True,False,1995
"American President, The (1995)",11,False,False,True,False,True,False,False,False,False,False,1995
Dracula: Dead and Loving It (1995),12,False,False,True,False,False,False,True,False,False,False,1995
Balto (1995),13,False,True,False,False,False,False,False,False,False,False,1995
Nixon (1995),14,False,False,False,False,True,False,False,False,False,False,1995
Cutthroat Island (1995),15,True,True,False,False,False,False,False,False,False,False,1995
Casino (1995),16,False,False,False,True,True,False,False,False,False,False,1995
Sense and Sensibility (1995),17,False,False,False,False,True,False,False,False,False,False,1995
Four Rooms (1995),18,False,False,True,False,False,False,False,False,False,False,1995
Ace Ventura: When Nature Calls (1995),19,False,False,True,False,False,False,False,False,False,False,1995
Money Train (1995),20,True,False,True,True,True,False,False,False,True,False,1995
Get Shorty (1995),21,False,False,True,True,False,False,False,False,True,False,1995
Copycat (1995),22,False,False,False,True,True,False,True,True,True,False,1995
Assassins (1995),23,True,False,False,True,False,False,False,False,True,False,1995
Powder (1995),24,False,False,False,False,True,False,False,False,False,False,1995
Leaving Las Vegas (1995),25,False,False,False,False,True,False,False,False,False,False,1995
Othello (1995),26,False,False,False,False,True,False,False,False,False,False,1995
Now and Then (1995),27,False,False,False,False,True,False,False,False,False,False,1995
Persuasion (1995),28,False,False,False,False,True,False,False,False,False,False,1995
"City of Lost Children, The (Cité des enfants perdus, La) (1995)",29,False,True,False,False,True,False,False,True,False,False,1995
Shanghai Triad (Yao a yao yao dao waipo qiao) (1995),30,False,False,False,True,True,False,False,False,False,False,1995
...,...,...,...,...,...,...,...,...,...,...,...,...
Teenage Mutant Ninja Turtles: Out of the Shadows (2016),159690,True,True,True,False,False,False,False,False,False,False,2016
Popstar: Never Stop Never Stopping (2016),159755,False,False,True,False,False,False,False,False,False,False,2016
The Conjuring 2 (2016),159858,False,False,False,False,False,False,True,False,False,False,2016
Approaching the Unknown (2016),159972,False,False,False,False,True,False,False,False,True,False,2016
Ghostbusters (2016),160080,True,False,True,False,False,False,True,False,False,False,2016
Central Intelligence (2016),160271,True,False,True,False,False,False,False,False,False,False,2016
Jason Bourne (2016),160438,True,False,False,False,False,False,False,False,False,False,2016
The Maid's Room (2014),160440,False,False,False,False,False,False,False,False,True,False,2014
The Legend of Tarzan (2016),160563,True,True,False,False,False,False,False,False,False,False,2016
The Purge: Election Year (2016),160565,True,False,False,False,False,False,True,False,False,False,2016
Mike & Dave Need Wedding Dates (2016),160567,False,False,True,False,False,False,False,False,False,False,2016
Survive and Advance (2013),160590,False,False,False,False,False,False,False,False,False,False,2013
Tallulah (2016),160656,False,False,False,False,True,False,False,False,False,False,2016
Piper (2016),160718,False,False,False,False,False,False,False,False,False,False,2016
Nerve (2016),160954,False,False,False,False,True,False,False,False,True,False,2016
My Friend Rockefeller (2015),161084,False,False,False,False,False,False,False,False,False,False,2015
Sunspring (2016),161155,False,False,False,False,False,False,False,False,False,False,2016
Author: The JT LeRoy Story (2016),161336,False,False,False,False,False,False,False,False,False,False,2016
Hell or High Water (2016),161582,False,False,False,True,True,False,False,False,False,False,2016
Kingsglaive: Final Fantasy XV (2016),161594,True,True,False,False,True,False,False,False,False,False,2016
Body (2015),161830,False,False,False,False,True,False,True,False,True,False,2015
Sharknado 4: The 4th Awakens (2016),161918,True,True,False,False,False,False,True,False,False,False,2016
The Last Brickmaker in America (2001),161944,False,False,False,False,True,False,False,False,False,False,2001
Stranger Things,162376,False,False,False,False,True,False,False,False,False,False,NaN
Rustom (2016),162542,False,False,False,False,False,False,False,False,True,False,2016
Mohenjo Daro (2016),162672,False,True,False,False,True,False,False,False,False,False,2016
Shin Godzilla (2016),163056,True,True,False,False,False,False,False,False,False,False,2016
The Beatles: Eight Days a Week - The Touring Years (2016),163949,False,False,False,False,False,False,False,False,False,False,2016
The Gay Desperado (1936),164977,False,False,True,False,False,False,False,False,False,False,1936
"Women of '69, Unboxed",164979,False,False,False,False,False,False,False,False,False,False,NaN

In [126]:
pd.DataFrame(filtered_results,columns=['SimilarityScore'])

                                                    RecommendationScore
Jurassic Park (1993)                                          16.678243
Toy Story (1995)                                              15.568640
Star Wars: Episode IV - A New Hope (1977)                     15.248237
Raiders of the Lost Ark (Indiana Jones and the ...            13.782332
Back to the Future (1985)                                     13.613303
Star Wars: Episode V - The Empire Strikes Back ...            11.985316
Lord of the Rings: The Fellowship of the Ring, ...            11.300383
Lion King, The (1994)                                         10.432855
Independence Day (a.k.a. ID4) (1996)                           9.613008
Lord of the Rings: The Two Towers, The (2002)                  9.468344
Matrix, The (1999)                                             9.346084
Dances with Wolves (1990)                                      8.612609
Fargo (1996)                                                   7.787533
Shrek (2001)                                                   7.470805
E.T. the Extra-Terrestrial (1982)                              6.959453
True Lies (1994)                                               6.847852
Apollo 13 (1995)                                               6.570148
Gladiator (2000)                                               6.546923
Usual Suspects, The (1995)                                     6.513178
Terminator 2: Judgment Day (1991)                              6.438947
Seven (a.k.a. Se7en) (1995)                                    5.991121
Ace Ventura: Pet Detective (1994)                              5.903033
Good Will Hunting (1997)                                       5.663343
Groundhog Day (1993)                                           5.611809
Die Hard (1988)                                                5.474117
Godfather, The (1972)                                          5.354687
Mask, The (1994)                                               5.187759
Mrs. Doubtfire (1993)                                          5.064983
Dumb & Dumber (Dumb and Dumber) (1994)                         5.051165
Terminator, The (1984)                                         4.173230
Pretty Woman (1990)                                            3.717725
Babe (1995)                                                    3.667345
Twelve Monkeys (a.k.a. 12 Monkeys) (1995)                      3.525210
Indiana Jones and the Last Crusade (1989)                      3.241530
Fugitive, The (1993)                                           2.788352
Die Hard: With a Vengeance (1995)                              2.755249
Ghost (1990)                                                   2.585878
One Flew Over the Cuckoo's Nest (1975)                         2.448850
Reservoir Dogs (1992)                                          2.372018
Truman Show, The (1998)                                        2.296710
Star Wars: Episode I - The Phantom Menace (1999)               2.185591
Monty Python and the Holy Grail (1975)                         2.114956
Goodfellas (1990)                                              1.967638
Home Alone (1990)                                              1.908440
Interview with the Vampire: The Vampire Chronic...             1.904089
Stargate (1994)                                                1.896548
Memento (2000)                                                 1.875949
Ocean's Eleven (2001)                                          1.677435
Mission: Impossible (1996)                                     1.587954
Sleepless in Seattle (1993)                                    1.578389
Léon: The Professional (a.k.a. The Professional...             1.450572
Ferris Bueller's Day Off (1986)                                1.269489
Four Weddings and a Funeral (1994)                             1.090645
Clear and Present Danger (1994)                                1.084366
Pirates of the Caribbean: The Curse of the Blac...             0.962370
Clueless (1995)                                                0.954752
Firm, The (1993)                                               0.918963
Batman Forever (1995)                                          0.908869
GoldenEye (1995)                                               0.776046

In [159]:
merged_results = pd.merge(movies_df.set_index('title'),pd.DataFrame(filtered_results,columns=['SimilarityScore']),how='outer', left_index=True, right_index=True)

In [160]:
merged_results.dropna().sort_values(by=['SimilarityScore'],ascending=False)

,movieId,Action,Adventure,Comedy,Crime,Drama,Film-Noir,Horror,Mystery,Thriller,Western,Year,SimilarityScore
Jurassic Park (1993),480,True,True,False,False,False,False,False,False,True,False,1993,16.678243
Toy Story (1995),1,False,True,True,False,False,False,False,False,False,False,1995,15.568640
Star Wars: Episode IV - A New Hope (1977),260,True,True,False,False,False,False,False,False,False,False,1977,15.248237
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981),1198,True,True,False,False,False,False,False,False,False,False,1981,13.782332
Back to the Future (1985),1270,False,True,True,False,False,False,False,False,False,False,1985,13.613303
Star Wars: Episode V - The Empire Strikes Back (1980),1196,True,True,False,False,False,False,False,False,False,False,1980,11.985316
"Lord of the Rings: The Fellowship of the Ring, The (2001)",4993,False,True,False,False,False,False,False,False,False,False,2001,11.300383
"Lion King, The (1994)",364,False,True,False,False,True,False,False,False,False,False,1994,10.432855
Independence Day (a.k.a. ID4) (1996),780,True,True,False,False,False,False,False,False,True,False,1996,9.613008
"Lord of the Rings: The Two Towers, The (2002)",5952,False,True,False,False,False,False,False,False,False,False,2002,9.468344
"Matrix, The (1999)",2571,True,False,False,False,False,False,False,False,True,False,1999,9.346084
Dances with Wolves (1990),590,False,True,False,False,True,False,False,False,False,True,1990,8.612609
Fargo (1996),608,False,False,True,True,True,False,False,False,True,False,1996,7.787533
Shrek (2001),4306,False,True,True,False,False,False,False,False,False,False,2001,7.470805
E.T. the Extra-Terrestrial (1982),1097,False,False,False,False,True,False,False,False,False,False,1982,6.959453
True Lies (1994),380,True,True,True,False,False,False,False,False,True,False,1994,6.847852
Apollo 13 (1995),150,False,True,False,False,True,False,False,False,False,False,1995,6.570148
Gladiator (2000),3578,True,True,False,False,True,False,False,False,False,False,2000,6.546923
"Usual Suspects, The (1995)",50,False,False,False,True,False,False,False,True,True,False,1995,6.513178
Terminator 2: Judgment Day (1991),589,True,False,False,False,False,False,False,False,False,False,1991,6.438947
Seven (a.k.a. Se7en) (1995),47,False,False,False,False,False,False,False,True,True,False,1995,5.991121
Ace Ventura: Pet Detective (1994),344,False,False,True,False,False,False,False,False,False,False,1994,5.903033
Good Will Hunting (1997),1704,False,False,False,False,True,False,False,False,False,False,1997,5.663343
Groundhog Day (1993),1265,False,False,True,False,False,False,False,False,False,False,1993,5.611809
Die Hard (1988),1036,True,False,False,True,False,False,False,False,True,False,1988,5.474117
"Godfather, The (1972)",858,False,False,False,True,True,False,False,False,False,False,1972,5.354687
"Mask, The (1994)",367,True,False,True,True,False,False,False,False,False,False,1994,5.187759
Mrs. Doubtfire (1993),500,False,False,True,False,True,False,False,False,False,False,1993,5.064983
Dumb & Dumber (Dumb and Dumber) (1994),231,False,True,True,False,False,False,False,False,False,False,1994,5.051165
"Terminator, The (1984)",1240,True,False,False,False,False,False,False,False,True,False,1984,4.173230
Pretty Woman (1990),597,False,False,True,False,False,False,False,False,False,False,1990,3.717725
Babe (1995),34,False,False,False,False,True,False,False,False,False,False,1995,3.667345
Twelve Monkeys (a.k.a. 12 Monkeys) (1995),32,False,False,False,False,False,False,False,True,True,False,1995,3.525210
Indiana Jones and the Last Crusade (1989),1291,True,True,False,False,False,False,False,False,False,False,1989,3.241530
"Fugitive, The (1993)",457,False,False,False,False,False,False,False,False,True,False,1993,2.788352
Die Hard: With a Vengeance (1995),165,True,False,False,True,False,False,False,False,True,False,1995,2.755249
Ghost (1990),587,False,False,True,False,True,False,False,False,True,False,1990,2.585878
One Flew Over the Cuckoo's Nest (1975),1193,False,False,False,False,True,False,False,False,False,False,1975,2.448850
Reservoir Dogs (1992),1089,False,False,False,True,False,False,False,True,True,False,1992,2.372018
"Truman Show, The (1998)",1682,False,False,True,False,True,False,False,False,False,False,1998,2.296710
Star Wars: Episode I - The Phantom Menace (1999),2628,True,True,False,False,False,False,False,False,False,False,1999,2.185591
Monty Python and the Holy Grail (1975),1136,False,True,True,False,False,False,False,False,False,False,1975,2.114956
Goodfellas (1990),1213,False,False,False,True,True,False,False,False,False,False,1990,1.967638
Home Alone (1990),586,False,False,True,False,False,False,False,False,False,False,1990,1.908440
Interview with the Vampire: The Vampire Chronicles (1994),253,False,False,False,False,True,False,True,False,False,False,1994,1.904089
Stargate (1994),316,True,True,False,False,False,False,False,False,False,False,1994,1.896548
Memento (2000),4226,False,False,False,False,False,False,False,True,True,False,2000,1.875949
Ocean's Eleven (2001),4963,False,False,False,True,False,False,False,False,True,False,2001,1.677435
Mission: Impossible (1996),648,True,True,False,False,False,False,False,True,True,False,1996,1.587954
Sleepless in Seattle (1993),539,False,False,True,False,True,False,False,False,False,False,1993,1.578389
Léon: The Professional (a.k.a. The Professional) (Léon) (1994),293,True,False,False,True,True,False,False,False,True,False,1994,1.450572
Ferris Bueller's Day Off (1986),2918,False,False,True,False,False,False,False,False,False,False,1986,1.269489
Four Weddings and a Funeral (1994),357,False,False,True,False,False,False,False,False,False,False,1994,1.090645
Clear and Present Danger (1994),349,True,False,False,True,True,False,False,False,True,False,1994,1.084366
Pirates of the Caribbean: The Curse of the Black Pearl (2003),6539,True,True,True,False,False,False,False,False,False,False,2003,0.962370
Clueless (1995),39,False,False,True,False,False,False,False,False,False,False,1995,0.954752
"Firm, The (1993)",454,False,False,False,False,True,False,False,False,True,False,1993,0.918963
Batman Forever (1995),153,True,True,True,True,False,False,False,False,False,False,1995,0.908869
GoldenEye (1995),10,True,True,False,False,False,False,False,False,True,False,1995,0.776046

In [161]:
def search(searchString):
    filter = merged_results.index.str.contains(searchString)
    return merged_results[filter].dropna().sort_values(by=['SimilarityScore'],ascending=False)

In [165]:
search('The')

,movieId,Action,Adventure,Comedy,Crime,Drama,Film-Noir,Horror,Mystery,Thriller,Western,Year,SimilarityScore
Star Wars: Episode V - The Empire Strikes Back (1980),1196,True,True,False,False,False,False,False,False,False,False,1980,11.985316
"Lord of the Rings: The Fellowship of the Ring, The (2001)",4993,False,True,False,False,False,False,False,False,False,False,2001,11.300383
"Lion King, The (1994)",364,False,True,False,False,True,False,False,False,False,False,1994,10.432855
"Lord of the Rings: The Two Towers, The (2002)",5952,False,True,False,False,False,False,False,False,False,False,2002,9.468344
"Matrix, The (1999)",2571,True,False,False,False,False,False,False,False,True,False,1999,9.346084
"Usual Suspects, The (1995)",50,False,False,False,True,False,False,False,True,True,False,1995,6.513178
"Godfather, The (1972)",858,False,False,False,True,True,False,False,False,False,False,1972,5.354687
"Mask, The (1994)",367,True,False,True,True,False,False,False,False,False,False,1994,5.187759
"Terminator, The (1984)",1240,True,False,False,False,False,False,False,False,True,False,1984,4.173230
"Fugitive, The (1993)",457,False,False,False,False,False,False,False,False,True,False,1993,2.788352
"Truman Show, The (1998)",1682,False,False,True,False,True,False,False,False,False,False,1998,2.296710
Star Wars: Episode I - The Phantom Menace (1999),2628,True,True,False,False,False,False,False,False,False,False,1999,2.185591
Interview with the Vampire: The Vampire Chronicles (1994),253,False,False,False,False,True,False,True,False,False,False,1994,1.904089
Léon: The Professional (a.k.a. The Professional) (Léon) (1994),293,True,False,False,True,True,False,False,False,True,False,1994,1.450572
Pirates of the Caribbean: The Curse of the Black Pearl (2003),6539,True,True,True,False,False,False,False,False,False,False,2003,0.962370
"Firm, The (1993)",454,False,False,False,False,True,False,False,False,True,False,1993,0.918963